language: csharp
mono: none
solution: OrderSystemForTBS.sln
dotnet: 2.0.0
dist: trusty
script:
- cd Backend/OrderSystemForTBS
- dotnet test UnitTest/UnitTest.csproj
- dotnet build
- dotnet restore
branches:
  only:
  - master
  - Development
notifications:
  email: false
before_install:
  - sudo apt-get install nunit-console
after_script:
  - nunit-console Tests/bin/Release/Tests.dll

