language: csharp
mono: none
solution: OrderSystemForTBS.sln
dotnet: 2.0.0
dist: trusty
install:
- dotnet restore
script:
- cd Backend/OrderSystemForTBS
- dotnet build
branches:
  only:
  - master
  - Development
notifications:
  email: false
